// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// This project keeps its env vars in .env.local (Next.js convention);
// fall back to .env for parity with the reference repo.
config({ path: [".env.local", ".env"] });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx scripts/seed-system-voices.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
